version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8084:8084
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/userService?allowPublicKeyRetrieval=true    
    depends_on:
      - mysqldb
    
    volumes:
      - .m2:/root/.m2
      
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3307
    networks:
      - springapimysql-net  
    environment:
      MYSQL_DATABASE: userService
      MYSQL_USER: root
      MYSQL_PASSWORD: Rinriy@1997
      MYSQL_ROOT_PASSWORD: Rinriy@1997
networks:
  springapimysql-net: